"""Add payment_methods table and trial fields

Revision ID: 405b3571ccf9
Revises: 78ec57ce4567
Create Date: 2026-01-04 00:52:58.675460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405b3571ccf9'
down_revision = '78ec57ce4567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('try_on_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('products_tried_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_sessions_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_expiry', sa.String(length=10), nullable=True),
    sa.Column('card_holder_name', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_subscription_id'), ['subscription_id'], unique=False)

    op.create_table('try_on_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('tried_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['try_on_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_events_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('default_payment_method_id', sa.Integer(), nullable=True))
        batch_op.drop_column('payment_method_brand')
        batch_op.drop_column('payment_method_type')
        batch_op.drop_column('payment_method_last4')
        batch_op.drop_column('payment_method_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method_expiry', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method_last4', sa.VARCHAR(length=4), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_method_brand', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('default_payment_method_id')
        batch_op.drop_column('trial_ends_at')

    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_events_session_id'))

    op.drop_table('try_on_events')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_subscription_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_sessions_outlet_id'))

    op.drop_table('try_on_sessions')
    # ### end Alembic commands ###
