"""Add subscriptions and invoices tables

Revision ID: 78ec57ce4567
Revises: eaf1cb5a5352
Create Date: 2026-01-04 00:27:54.053009

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78ec57ce4567'
down_revision = 'eaf1cb5a5352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=True),
    sa.Column('plan_price', sa.Float(), nullable=True),
    sa.Column('billing_cycle', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method_type', sa.String(length=20), nullable=True),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True),
    sa.Column('payment_method_brand', sa.String(length=20), nullable=True),
    sa.Column('payment_method_expiry', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_outlet_id'), ['outlet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_subscription_id'), ['subscription_id'], unique=False)

    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_events_session_id'))

    op.drop_table('try_on_events')
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_sessions_outlet_id'))

    op.drop_table('try_on_sessions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('try_on_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('try_on_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('outlet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('kiosk_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('products_tried_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], name='try_on_sessions_outlet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='try_on_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_sessions_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('try_on_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('product_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('product_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('tried_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('try_on_events_product_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['try_on_sessions.id'], name=op.f('try_on_events_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('try_on_events_pkey'))
    )
    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_events_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_outlet_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_outlet_id'))

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
