"""Add sessions and events tables

Revision ID: eaf1cb5a5352
Revises: e1d7547fca2f
Create Date: 2026-01-04 00:12:11.706813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaf1cb5a5352'
down_revision = 'e1d7547fca2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('try_on_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('outlet_id', sa.Integer(), nullable=False),
    sa.Column('kiosk_id', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('products_tried_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['outlet_id'], ['outlets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_sessions_outlet_id'), ['outlet_id'], unique=False)

    op.create_table('try_on_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=50), nullable=True),
    sa.Column('product_type', sa.String(length=20), nullable=True),
    sa.Column('tried_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['try_on_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_try_on_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('try_on_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_events_session_id'))

    op.drop_table('try_on_events')
    with op.batch_alter_table('try_on_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_try_on_sessions_outlet_id'))

    op.drop_table('try_on_sessions')
    # ### end Alembic commands ###
