"""Add vouchers table and invoice voucher fields

Revision ID: f95c0e2458d5
Revises: 405b3571ccf9
Create Date: 2026-01-04 01:15:47.296682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95c0e2458d5'
down_revision = '405b3571ccf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vouchers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('applicable_plans', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vouchers_code'), ['code'], unique=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voucher_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('voucher_code')

    with op.batch_alter_table('vouchers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vouchers_code'))

    op.drop_table('vouchers')
    # ### end Alembic commands ###
